version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"
  apt_packages:
    - g++
    - libhdf5-dev
    - libpng-dev
  jobs:
    post_checkout:
      - git fetch --unshallow || true
sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
