#!/bin/bash
# Run previously-passing tests and stop at the first regression.
# Reads test IDs from passing_tests.txt (generated by record_tests.sh).
#
# Tests are run file-by-file with up to 8 running concurrently (1 thread each).
# As each test file finishes, the next one is dispatched immediately.
# Stops at the first regression.
#
# Usage:
#   ./check_tests.sh [options]
#
# Options:
#   --smoke    Randomly sample ~10% of test files
#   -q         Quiet mode: only progress counters and final result

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PASSING_FILE="$SCRIPT_DIR/passing_tests.txt"
MAX_JOBS=8

# Parse arguments
SMOKE=false
QUIET=false
for arg in "$@"; do
    case "$arg" in
        --smoke) SMOKE=true ;;
        -q)      QUIET=true ;;
    esac
done

if [[ ! -f "$PASSING_FILE" ]]; then
    echo "Error: $PASSING_FILE not found."
    echo "Run ./record_tests.sh first to generate the baseline."
    exit 1
fi

# Build clean list of expected-passing tests
EXPECTED_FILE=$(mktemp)
grep -v '^#' "$PASSING_FILE" | grep -v '^$' > "$EXPECTED_FILE"
TOTAL=$(wc -l < "$EXPECTED_FILE" | tr -d ' ')

if [[ "$TOTAL" -eq 0 ]]; then
    echo "Error: No tests found in $PASSING_FILE"
    rm -f "$EXPECTED_FILE"
    exit 1
fi

# Get unique test files
ALL_FILES=($(cut -d: -f1 "$EXPECTED_FILE" | sort -u))
NUM_FILES=${#ALL_FILES[@]}

cd "$SCRIPT_DIR"

if $SMOKE; then
    SAMPLE_SIZE=$(( NUM_FILES / 10 ))
    [[ "$SAMPLE_SIZE" -lt 1 ]] && SAMPLE_SIZE=1

    FILES=($(python3 -c "
import random, sys
k = int(sys.argv[1])
files = sys.argv[2:]
selected = random.sample(files, k)
for f in sorted(selected):
    print(f)
" "$SAMPLE_SIZE" "${ALL_FILES[@]}"))

    echo "=== Smoke test: ${#FILES[@]} / $NUM_FILES test files ==="
else
    FILES=("${ALL_FILES[@]}")
    echo "=== Running $NUM_FILES test files ($TOTAL expected passing, $MAX_JOBS parallel) ==="
fi

TMPDIR=$(mktemp -d)
CHECKED=0
COMPLETED=0
REGRESSION=""
NEXT=0

cleanup() {
    rm -rf "$TMPDIR" "$EXPECTED_FILE"
}
trap cleanup EXIT

# Check results for a completed test file. Sets REGRESSION on failure.
check_file() {
    local FILE="$1"
    local OUTFILE="$TMPDIR/$(echo "$FILE" | tr '/' '_')"
    local OUTPUT=$(<"$OUTFILE")

    # Show per-test results unless quiet
    if ! $QUIET; then
        echo "$OUTPUT" | grep -E "(PASSED|FAILED)" | grep -v "^=" || true
    fi

    # Check expected-passing tests in this file
    while IFS= read -r test_id; do
        CHECKED=$((CHECKED + 1))
        if ! echo "$OUTPUT" | grep -qF "$test_id PASSED"; then
            REGRESSION="$test_id"
            return 1
        fi
    done < <(grep "^${FILE}::" "$EXPECTED_FILE")
    return 0
}

# Launch a test file in the background, adding to NEW_PIDS/NEW_PID_FILES
launch_into() {
    local FILE="${FILES[$NEXT]}"
    local OUTFILE="$TMPDIR/$(echo "$FILE" | tr '/' '_')"
    OMP_NUM_THREADS=1 python -m pytest "$FILE" -v --tb=short > "$OUTFILE" 2>&1 &
    NEW_PIDS+=($!)
    NEW_PID_FILES+=("$FILE")
    NEXT=$((NEXT + 1))
}

# Fill initial slots
PIDS=()
PID_FILES=()
NEW_PIDS=()
NEW_PID_FILES=()
while [[ $NEXT -lt ${#FILES[@]} && ${#NEW_PIDS[@]} -lt $MAX_JOBS ]]; do
    launch_into
done
PIDS=("${NEW_PIDS[@]}")
PID_FILES=("${NEW_PID_FILES[@]}")

# Process completions and dispatch new work
while [[ ${#PIDS[@]} -gt 0 ]]; do
    sleep 1

    # Snapshot the current arrays (don't modify while iterating)
    CURRENT_PIDS=("${PIDS[@]}")
    CURRENT_FILES=("${PID_FILES[@]}")
    NEW_PIDS=()
    NEW_PID_FILES=()
    BATCH_COMPLETED=0

    for ((k=0; k<${#CURRENT_PIDS[@]}; k++)); do
        if ! kill -0 "${CURRENT_PIDS[$k]}" 2>/dev/null; then
            # This one finished — check its results
            COMPLETED=$((COMPLETED + 1))
            BATCH_COMPLETED=$((BATCH_COMPLETED + 1))
            check_file "${CURRENT_FILES[$k]}"
            if [[ -n "$REGRESSION" ]]; then
                # Kill remaining jobs
                for pid in "${CURRENT_PIDS[@]}"; do
                    kill "$pid" 2>/dev/null || true
                done
                wait 2>/dev/null
                # Save full pytest output for the failing file
                FAIL_OUTFILE="$TMPDIR/$(echo "${CURRENT_FILES[$k]}" | tr '/' '_')"
                cp "$FAIL_OUTFILE" /tmp/openmc_regression.txt

                echo ""
                echo "=== REGRESSION DETECTED ($COMPLETED / ${#FILES[@]} files) ==="
                echo ""
                echo "  $REGRESSION"
                echo ""
                echo "Details: /tmp/openmc_regression.txt"
                exit 1
            fi

            # Dispatch next file if available
            if [[ $NEXT -lt ${#FILES[@]} ]]; then
                launch_into
            fi
        else
            # Still running — keep it
            NEW_PIDS+=("${CURRENT_PIDS[$k]}")
            NEW_PID_FILES+=("${CURRENT_FILES[$k]}")
        fi
    done

    PIDS=("${NEW_PIDS[@]}")
    PID_FILES=("${NEW_PID_FILES[@]}")

    if [[ $BATCH_COMPLETED -gt 0 ]]; then
        echo "  [$COMPLETED / ${#FILES[@]} files done]"
    fi
done

echo ""
echo "=== ALL $CHECKED TESTS PASSED (no regressions) ==="
