set (CTEST_SOURCE_DIRECTORY "/home/wboyd/Desktop/openmc/tests/../src")
set (CTEST_BINARY_DIRECTORY "/home/wboyd/Desktop/openmc/tests/build")

set(CTEST_SITE "wboyd-ThinkPad-X230")
set (CTEST_BUILD_NAME "_phdf5-omp-debug")
set (CTEST_CMAKE_GENERATOR "Unix Makefiles")
set (CTEST_BUILD_OPTIONS "-Ddebug=ON -Dopenmp=ON ")

set(CTEST_UPDATE_COMMAND "git")

set(CTEST_CONFIGURE_COMMAND "${CMAKE_COMMAND} -H${CTEST_SOURCE_DIRECTORY} -B${CTEST_BINARY_DIRECTORY} ${CTEST_BUILD_OPTIONS}")
set(CTEST_MEMORYCHECK_COMMAND "")
set(CTEST_MEMORYCHECK_COMMAND_OPTIONS "--tool=memcheck --leak-check=yes --show-reachable=yes --num-callers=20 --track-fds=yes")
set(CTEST_MEMORYCHECK_SUPPRESSIONS_FILE ${CTEST_SOURCE_DIRECTORY}/../tests/valgrind.supp)
set(MEM_CHECK False)
set(ENV{MEM_CHECK} ${MEM_CHECK})

set(CTEST_COVERAGE_COMMAND "")
set(COVERAGE False)
set(ENV{COVERAGE} ${COVERAGE})



ctest_start("Experimental")
ctest_configure(RETURN_VALUE res)

ctest_build(RETURN_VALUE res)
ctest_test( PARALLEL_LEVEL 4, RETURN_VALUE res)
if(MEM_CHECK)
ctest_memcheck(, RETURN_VALUE res)
endif(MEM_CHECK)
if(COVERAGE)
ctest_coverage(RETURN_VALUE res)
endif(COVERAGE)


if (res EQUAL 0)
else()
message(FATAL_ERROR "")
endif()
