#!/usr/bin/env python

from openmc.ace import ascii_to_binary
import sys


if __name__ == '__main__':
    # Check for proper number of arguments
    if len(sys.argv) < 3:
        sys.exit('Usage: {0} ascii_file binary_file'.format(sys.argv[0]))

    # Convert ASCII file
    ascii_to_binary(sys.argv[1], sys.argv[2])
