#!/usr/bin/env python3

"""Combine multiple HDF5 particle track files.

"""

import argparse

import h5py


def main():
    # Parse command-line arguments
    parser = argparse.ArgumentParser(
        description='Combine particle track files into a single .h5 file.')
    parser.add_argument('input', metavar='IN', nargs='+',
                        help='Input HDF5 particle track filename(s).')
    parser.add_argument('-o', '--out', metavar='OUT', default='tracks.h5',
                        help='Output HDF5 particle track file.')

    args = parser.parse_args()

    with h5py.File(args.out, 'w') as h5_out:
        for i, fname in enumerate(args.input):
            with h5py.File(fname, 'r') as h5_in:
                # Copy file attributes for first file
                if i == 0:
                    h5_out.attrs['filetype'] = h5_in.attrs['filetype']
                    h5_out.attrs['version'] = h5_in.attrs['version']

                # Copy each 'track_*' dataset from input file
                for dset in h5_in:
                    h5_in.copy(dset, h5_out)


if __name__ == '__main__':
    main()
