module purxs_api
#ifdef PURXS
  use URR_endf6,     only:&
       URR_read_endf6 => read_endf6
  use URR_error, only:&
       URR_EXIT_SUCCESS => EXIT_SUCCESS,&
       URR_EXIT_FAILURE => EXIT_FAILURE,&
       URR_EXIT_WARNING => EXIT_WARNING
  use URR_faddeeva,  only:&
       URR_tabulate_w => tabulate_w
  use URR_io,        only:&
       URR_read_point_xs => read_point_xs,&
       URR_read_prob_tables => read_prob_tables,&
       URR_write_MF2 => write_MF2
  use URR_isotope,   only:&
       URR_Type_Isotope => Isotope,&
       URR_isotopes => isotopes
  use URR_constants, only:&
       URR_E_NEUTRON => E_NEUTRON,&
       URR_SLBW => SLBW,&
       URR_MLBW => MLBW,&
       URR_REICH_MOORE => REICH_MOORE,&
       URR_MNBW => MNBW,&
       URR_ENDF6 => ENDF6,&
       URR_USER => USER,&
       URR_ENDFFILE => ENDFFILE,&
       URR_FALSE => FALSE,&
       URR_ZERO => ZERO,&
       URR_INF => INF,&
       URR_LINEAR => LINEAR,&
       URR_LOGARITHMIC => LOGARITHMIC,&
       URR_HISTOGRAM => HISTOGRAM,&
       URR_LINEAR_LINEAR => LINEAR_LINEAR,&
       URR_LINEAR_LOG => LINEAR_LOG,&
       URR_LOG_LINEAR => LOG_LINEAR,&
       URR_LOG_LOG => LOG_LOG,&
       URR_SQRT_LINEAR => SQRT_LINEAR,&
       URR_SQRT_LOG => SQRT_LOG,&
       URR_STATISTICAL => STATISTICAL,&
       URR_LOW_NEIGHBOR => LOW_NEIGHBOR,&
       URR_MIT_W => MIT_W,&
       URR_QUICK_W => QUICK_W,&
       URR_ON_THE_FLY => ON_THE_FLY,&
       URR_PROB_BANDS => PROB_BANDS,&
       URR_POINTWISE => POINTWISE,&
       URR_EVENT => EVENT,&
       URR_HISTORY => HISTORY,&
       URR_BATCH => BATCH,&
       URR_SIMULATION => SIMULATION,&
       URR_E_RESONANCE => E_RESONANCE,&
       URR_RECONSTRUCTION => RECONSTRUCTION,&
       URR_HDF5 => HDF5
  use URR_settings,  only:&
       URR_num_isotopes => num_isotopes,&
       URR_parameter_energy_dependence => parameter_energy_dependence,&
       URR_use_urr => use_urr,&
       URR_realization_frequency => realization_frequency,&
       URR_endf_filenames => endf_filenames,&
       URR_formalism => formalism,&
       URR_T_grid_prob_tables => T_grid_prob_tables,&
       URR_E_grid_prob_tables => E_grid_prob_tables,&
       URR_num_l_waves => num_l_waves,&
       URR_faddeeva_method => faddeeva_method,&
       URR_write_avg_xs => write_avg_xs,&
       URR_write_prob_tables => write_prob_tables,&
       URR_background_xs_treatment => background_xs_treatment,&
       URR_competitive_structure => competitive_structure,&
       URR_E_grid_scheme_prob_tables => E_grid_scheme_prob_tables,&
       URR_i_realization_user => i_realization_user,&
       URR_temperature_interp_scheme => temperature_interp_scheme,&
       URR_pregenerated_prob_tables => pregenerated_prob_tables,&
       URR_num_energies_prob_tables => num_energies_prob_tables,&
       URR_num_temperatures_prob_tables => num_temperatures_prob_tables,&
       URR_num_bands_prob_tables => num_bands_prob_tables,&
       URR_num_histories_prob_tables => num_histories_prob_tables,&
       URR_rel_err_tolerance_avg_xs => rel_err_tolerance_avg_xs,&
       URR_realization_frequency => realization_frequency,&
       URR_pregenerated_point_xs => pregenerated_point_xs,&
       URR_rel_err_tolerance_pointwise => rel_err_tolerance_pointwise,&
       URR_xs_representation => xs_representation,&
       URR_min_num_batches_prob_tables => min_num_batches_prob_tables,&
       URR_max_num_batches_prob_tables => max_num_batches_prob_tables,&
       URR_min_delta_E_pointwise => min_delta_E_pointwise,&
       URR_num_urr_realizations => num_urr_realizations,&
       URR_path_avg_xs => path_avg_xs,&
       URR_path_point_xs => path_point_xs,&
       URR_path_prob_tables => path_prob_tables,&
       URR_path_endf_files => path_endf_files,&
       URR_parameter_energy_dependence => parameter_energy_dependence,&
       URR_xs_source_pointwise => xs_source_pointwise,&
       URR_temperature_pointwise => temperature_pointwise
  use URR_cross_Sections, only:&
       URR_Type_CrossSections => CrossSections
#endif
end module purxs_api
