/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ersn.openmc;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;

/**
 *
 * @author Geant4
 */
public class new_openmc_project extends javax.swing.JFrame {

    singleton tmp = singleton.getInstance( );


    public new_openmc_project() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _new_project = new javax.swing.JTextField();
        lbl_project_name = new javax.swing.JLabel();
        _workspace = new javax.swing.JTextField();
        lbl_workspace = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        select_settings = new javax.swing.JCheckBox();
        select_cmfd = new javax.swing.JCheckBox();
        select_materials = new javax.swing.JCheckBox();
        select_geometry = new javax.swing.JCheckBox();
        select_tallies = new javax.swing.JCheckBox();
        select_plotting = new javax.swing.JCheckBox();
        lbl_xml_files = new javax.swing.JLabel();
        btn_ok = new javax.swing.JButton();
        lbl_description = new javax.swing.JLabel();
        _description = new javax.swing.JTextField();
        lbl_case = new javax.swing.JLabel();
        _case = new javax.swing.JTextField();
        lbl_writen_by = new javax.swing.JLabel();
        _writen = new javax.swing.JTextField();
        lbl_date = new javax.swing.JLabel();
        _date = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New OpenMC project");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbl_project_name.setText("Project Name");

        lbl_workspace.setText("Workspace");

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        select_settings.setSelected(true);
        select_settings.setText("settings");
        select_settings.setEnabled(false);

        select_cmfd.setText("cmfd");

        select_materials.setSelected(true);
        select_materials.setText("materials");
        select_materials.setEnabled(false);

        select_geometry.setSelected(true);
        select_geometry.setText("geometry");
        select_geometry.setEnabled(false);

        select_tallies.setText("tallies");

        select_plotting.setText("plots");

        lbl_xml_files.setText("xml files");

        btn_ok.setText("OK");
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });

        lbl_description.setText("Description");

        lbl_case.setText("Case");

        lbl_writen_by.setText("Writen By");

        lbl_date.setText("Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_xml_files)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_workspace, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_project_name, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_description, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_case, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_date, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(_workspace)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton1))
                                .addComponent(_new_project)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(_case, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_description, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_writen, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_date, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(select_geometry)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(select_materials)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(select_settings)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(select_cmfd)
                                .addGap(18, 18, 18)
                                .addComponent(select_tallies)
                                .addGap(19, 19, 19)
                                .addComponent(select_plotting)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(btn_ok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_writen_by, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_new_project, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_project_name))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_workspace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_workspace)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_description)
                            .addComponent(_description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_case)
                            .addComponent(_case, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_writen_by)
                            .addComponent(_writen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_date)))
                .addGap(18, 18, 18)
                .addComponent(lbl_xml_files)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(select_materials)
                    .addComponent(select_settings)
                    .addComponent(select_geometry)
                    .addComponent(select_cmfd)
                    .addComponent(select_tallies)
                    .addComponent(select_plotting))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 35, Short.MAX_VALUE)
                .addComponent(btn_ok)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 
JFileChooser fc = new JFileChooser(); 
fc.setFileSelectionMode( JFileChooser.DIRECTORIES_ONLY);
int returnVal = fc.showOpenDialog(this);
if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION) {
    java.io.File file = fc.getSelectedFile( );
    String file_name = file.toString( );
  _workspace.setText(file_name);

 }  
    }//GEN-LAST:event_jButton1ActionPerformed
public void create_empty_xml_file(String xml_file, String target){

 try {
                    FileWriter lu = new FileWriter(_workspace.getText()+"/"+_new_project.getText()+"/"+xml_file);// Créer un objet java.io.FileWriter avec comme argument le mon du fichier dans lequel enregsitrer
                    BufferedWriter fluxS = new BufferedWriter(lu); // Mettre le flux en tampon (en cache)
                    fluxS.write(target); //Balancer dans le flux le contenu de la zone de texte
                    fluxS.close(); // Fermer le flux (c’est toujours mieux de le fermer explicitement)
                } catch (IOException er) {;
                
                System.out.print("!!!!!!!!!!");
                
                }
 
       
}
    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        // TODO add your handling code here:
     java.awt.EventQueue.invokeLater(new Runnable() {
          public void run() {
            
          main  dialgo  =new     main();

           dialgo.show();
           }
          
            
        }); 
     
      File dir = new File(_workspace.getText()+"/"+_new_project.getText());
           dir.mkdir();  

      tmp.setPath(_workspace.getText()+"/"+_new_project.getText());

String setting_init="<?xml version=\"1.0\"?>\n" +"<settings> \n"+"<!-- \n=========================================================================="+"\nDescription:"+_description.getText()+"  \nCase:"+_case.getText()+" \nWriten By:"+_writen.getText()+" \nDate:"+_date.getText()+"\n==========================================================================\n -->"+"\n \n \n \n</settings>";
String geometry_init="<?xml version=\"1.0\"?>\n" +"<geometry> \n"+"<!-- \n=========================================================================="+"\nDescription:"+_description.getText()+"  \nCase:"+_case.getText()+" \nWriten By:"+_writen.getText()+" \nDate:"+_date.getText()+"\n==========================================================================\n -->"+"\n \n \n \n</geometry>";
String materials_init="<?xml version=\"1.0\"?>\n" +"<materials> \n"+"<!-- \n=========================================================================="+"\nDescription:"+_description.getText()+"  \nCase:"+_case.getText()+" \nWriten By:"+_writen.getText()+" \nDate:"+_date.getText()+"\n==========================================================================\n -->"+"\n \n \n \n</materials>";
String tallies_init="<?xml version=\"1.0\"?>\n" +"<tallies> \n"+"<!-- \n=========================================================================="+"\nDescription:"+_description.getText()+"  \nCase:"+_case.getText()+" \nWriten By:"+_writen.getText()+" \nDate:"+_date.getText()+"\n==========================================================================\n -->"+"\n \n \n \n</tallies>";
String cmfd_init="<?xml version=\"1.0\"?>\n" +"<cmfd> \n"+"<!-- \n=========================================================================="+"\nDescription:"+_description.getText()+"  \nCase:"+_case.getText()+" \nWriten By:"+_writen.getText()+" \nDate:"+_date.getText()+"\n==========================================================================\n -->"+"\n \n \n \n</cmfd>";
String plots_init="<?xml version=\"1.0\"?>\n" +"<plots> \n"+"<!-- \n=========================================================================="+"\nDescription:"+_description.getText()+"  \nCase:"+_case.getText()+" \nWriten By:"+_writen.getText()+" \nDate:"+_date.getText()+"\n==========================================================================\n -->"+"\n \n \n \n</plots>";

create_empty_xml_file("settings.xml",setting_init);
create_empty_xml_file("geometry.xml",geometry_init);
create_empty_xml_file("materials.xml",materials_init);

if (select_tallies.isSelected()==true) create_empty_xml_file("tallies.xml",tallies_init);
if (select_cmfd.isSelected()==true) create_empty_xml_file("cmfd.xml",cmfd_init);
if (select_plotting.isSelected()==true) create_empty_xml_file("plots.xml",plots_init);

this.show(false);
        
    }//GEN-LAST:event_btn_okActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
Date date = new Date();
_date.setText(dateFormat.format(date));
        
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(new_openmc_project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(new_openmc_project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(new_openmc_project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(new_openmc_project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new new_openmc_project().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField _case;
    private javax.swing.JTextField _date;
    private javax.swing.JTextField _description;
    private javax.swing.JTextField _new_project;
    private javax.swing.JTextField _workspace;
    private javax.swing.JTextField _writen;
    private javax.swing.JButton btn_ok;
    private javax.swing.JButton jButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_case;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_description;
    private javax.swing.JLabel lbl_project_name;
    private javax.swing.JLabel lbl_workspace;
    private javax.swing.JLabel lbl_writen_by;
    private javax.swing.JLabel lbl_xml_files;
    private javax.swing.JCheckBox select_cmfd;
    private javax.swing.JCheckBox select_geometry;
    private javax.swing.JCheckBox select_materials;
    private javax.swing.JCheckBox select_plotting;
    private javax.swing.JCheckBox select_settings;
    private javax.swing.JCheckBox select_tallies;
    // End of variables declaration//GEN-END:variables
}
