name: dockerhub-publish-develop-dagmc-libmesh

on:
  push:
    branches: develop

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: openmc/openmc:develop-dagmc-libmesh
          build-args: |
            build_dagmc=on
            build_libmesh=on
            compile_cores=2
            openmc_branch=develop
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
