name: C++ Format Check

on:
  # allow workflow to be run manually
  workflow_dispatch:

  pull_request:
    branches:
      - develop
      - master

jobs:
  filter-cpp-changes:
    runs-on: ubuntu-latest
    outputs:
      cpp_status: ${{ steps.filter.outputs.cpp }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Examine changed files
        id: filter 
        uses: dorny/paths-filter@v3
        with:
          filters: |
            cpp: 
              - 'src/**/*.cpp' 
              - 'tests/**/*.cpp'
              - 'src/**/*.h' 
              - 'tests/**/*.h'
  cpp-linter:
    needs: filter-cpp-changes
    if: ${{ needs.filter-cpp-changes.outputs.cpp_status == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          files-changed-only: true
          tidy-checks: '-*'
          version: '15' # clang-format version
          file-annotations: true
          step-summary: true
          extensions: 'cpp,h'

      - name: Failure Check
        if: steps.linter.outputs.checks-failed > 0
        run: echo "Some files failed the formatting check! See job summary and file annotations for more info" && exit 1
